<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_linknaver</name>
   <tag></tag>
   <elementGuidId>3c88d6a3-0d78-457e-8b6e-60cae419838c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup-login']/div[2]/div/div/div[6]/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.naver-login > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-login&quot;)/div[@class=&quot;popup-contents&quot;]/div[@class=&quot;login-area&quot;]/div[@class=&quot;login flow&quot;]/div[@class=&quot;sns-list-wrap&quot;]/ul[@class=&quot;sns-list&quot;]/li[1]/a[@class=&quot;naver-login&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-login']/div[2]/div/div/div[6]/ul/li/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
   </webElementXpaths>
</WebElementEntity>
